---
- name: testing ansible training
  hosts: prod
  vars_files:
    - files/secrets/credentials.yml
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: install requirement
      yum:
        name: '{{ item }}'
        state: present
      when: ansible_distribution == 'CentOS'
      with_items: 
        - epel-release
        - wget
        - git
    - name: install pip
      yum:
        name: python-pip
        state: present
        update_cache: yes
    - name: install docker-py
      pip:
        name: docker-py
  tasks:
    - name: copy the index file
      template:
        src: index.html.j2
        dest: /home/admin/index.html
    - name: start a container
      docker_container:
        name: myapplication
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html            
