---
- name: install of httpd
  hosts: prod
  become: yes
  vars:
    ansible_sudo_pass: admin
  gather_facts: yes
  pre_tasks:
    - name: install epel-release
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS'
    - name: install pip
      yum:
        name: python-pip
        state: present
        update_cache: yes
    - name: install docker-py
      pip:
        name: docker-py
  tasks:
    - name: start a container
      docker_container:
        name: myapplication
        image: httpd
        ports:
          - "80:80"
     
