---
- name: testing ansible training
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml
  vars:
    system_user: admin  
  pre_tasks:
    - name: Install requirements
      user: 
        name: "www-data"
        state: present
  roles: 
    - { role: ansible-role-containerized-wordpress }

